// GENERATED by scripts/build-interpretation-reference.mjs. Do not edit by hand.
// Source of truth: docs/layer2-pairwise-interactions.md and docs/layer3-candidate-defaults.md.
// Regenerate after editing either document.

import type { InterpretationReference } from './types'

export const REFERENCE: InterpretationReference = {
  "source": {
    "layer2": "665d77720998",
    "layer3": "0517a23a703c"
  },
  "axes": [
    {
      "key": "social_attunement",
      "title": "Social Attunement",
      "high": "Hyper-Attuned",
      "low": "Hypo-Attuned"
    },
    {
      "key": "empathy",
      "title": "Empathy",
      "high": "Empathy",
      "low": "Detachment"
    },
    {
      "key": "self_orientation",
      "title": "Self-Orientation",
      "high": "Self-Focus",
      "low": "Altruism"
    },
    {
      "key": "conscientiousness",
      "title": "Conscientiousness",
      "high": "Conscientious",
      "low": "Impulsive"
    },
    {
      "key": "agency",
      "title": "Agency",
      "high": "Agentic",
      "low": "Accommodating"
    },
    {
      "key": "reactivity",
      "title": "Reactivity",
      "high": "High-Reactive",
      "low": "Low-Reactive"
    }
  ],
  "pairs": {
    "social_attunement|empathy": {
      "axes": [
        "social_attunement",
        "empathy"
      ],
      "anchors": {
        "high_high": {
          "name": "the read and the response",
          "text": "The perceptual scan (micro-expressions, vocal shifts, unspoken tension) is not just received but *matters*: each signal registers as something to act on rather than merely notice. This produces the \"people feel genuinely seen\" effect the book associates with high attunement, but with an added layer of felt concern, not just accurate perception. Risk profile: absorption — high input plus high moral pull can leave little bandwidth left over for the self."
        },
        "low_low": {
          "name": "flat terrain",
          "text": "Low signal in, low pull to respond even to what little comes through. Not dramatic coldness — closer to \"a perfectly pleasant evening\" without noticing there were undercurrents to miss, compounded by the fact that even a pointed-out undercurrent wouldn't generate much motivational charge. Reads as obliviousness rather than indifference, since there's no evidence of suppressed concern — the concern simply isn't being recruited."
        },
        "high_low": {
          "name": "precision without concern",
          "text": "The perceptual instrument is fully online; the moral pull is not. Signals are read with real accuracy but register as information rather than as a call to respond. What happens to that information depends on other axes: the same pair describes the skilled negotiator, the calm triage surgeon, and — combined with strong Self-Focus — the con artist the book describes. Easy to mistake for the first shape from the outside, since accuracy of the read can look like warmth."
        },
        "low_high": {
          "name": "caring for a signal you can't see",
          "text": "Genuine moral concern is active, but the perceptual input that would normally trigger it is thin. Produces a sympathetic failure mode: the person would care, and does care in general, but doesn't reliably notice the specific moment that calls for it. An explicit prompt (\"I need you right now\") reliably produces real engagement — distinguishing this from Hypo-Attuned + Detachment, where the same prompt would not."
        }
      }
    },
    "self_orientation|agency": {
      "axes": [
        "self_orientation",
        "agency"
      ],
      "anchors": {
        "low_high": {
          "name": "the directive server",
          "text": "Resources and priority flow outward, pursued assertively rather than passively — initiating structures or interventions on others' behalf rather than waiting for a request. Generosity here tends to be systematic and institution-building rather than personal and case-by-case. Risk: paternalism — assertiveness in service of someone else's interest can still override what that person actually wants (\"doing things for people rather than with them\")."
        },
        "high_low": {
          "name": "the quiet self-protector",
          "text": "Attention centers on the self's own interests, but these are pursued by going along rather than by asserting — avoiding conflict that would be costly, keeping a low profile, cooperating where it's safe and withdrawing where it isn't. Usually unremarkable: the colleague who protects their own position without making waves. The book's vulnerable-narcissism pattern sits at the far edge, where withdrawal becomes hypersensitivity to criticism and a concealed sense of entitlement. Can be mistaken for accommodation-as-altruism from outside; the distinguishing feature is that the going-along serves self-protection, not concern for the other party."
        },
        "high_high": {
          "name": "the architecture of self, asserted",
          "text": "Attention and resources concentrate on the self, pursued confidently and directively — a singular personal vision that others are expected to execute, held with intense concern for how it will be remembered. The book is explicit that ordinary high self-orientation plus agency (ambition, independence, competitiveness) is normal here; the pathological edge — the book's grandiose narcissism — appears specifically when other people's interests stop registering as a constraint at all."
        },
        "low_low": {
          "name": "service without a seat at the table",
          "text": "Other-directed motivation expressed through support rather than initiative — managing, stabilizing, absorbing risk on someone else's behalf, avoiding the spotlight rather than claiming it. Real, sustained generosity delivered by backing someone else's agenda rather than asserting one's own. Risk: invisibility — the contribution can be structurally essential and socially unrecognized at once."
        }
      }
    },
    "conscientiousness|reactivity": {
      "axes": [
        "conscientiousness",
        "reactivity"
      ],
      "anchors": {
        "high_high": {
          "name": "disciplined intensity",
          "text": "Strong emotional amplitude moves through structure rather than around it — planning and follow-through contain what would otherwise be volatile. Intensity shows up in the drive behind the work rather than in the reliability of the work itself."
        },
        "low_low": {
          "name": "easy drift",
          "text": "Low structure, low amplitude: decisions shift readily, but not because anything is emotionally charged — there's simply little friction holding a course in place. Reads as easygoing rather than chaotic; distinguish sharply from the fourth shape below, which shares the impulsivity but not the calm."
        },
        "high_low": {
          "name": "the steady hand",
          "text": "Structure without emotional amplification — closest to what most organizations describe as a reliable operator: plans hold, follow-through is consistent, none of it driven or disrupted by strong feeling. A disciplined, maintained regimen — the body and career treated as things to sustain rather than simply use up — is the book's pattern for this end."
        },
        "low_high": {
          "name": "combustible spontaneity",
          "text": "Low structural containment plus high emotional amplitude — chasing an impulse in the moment, with no plan and no safety net under it. The highest-volatility combination on this pair: real creative or interpersonal intensity, with the fewest internal guardrails once emotion moves it. Complementarity with a high-conscientiousness partner (structure supplied externally) is a recurring pattern the book associates with this anchor."
        }
      }
    },
    "empathy|self_orientation": {
      "axes": [
        "empathy",
        "self_orientation"
      ],
      "anchors": {
        "high_low": {
          "name": "the calling",
          "text": "Others' suffering registers as a moral pull that demands a response — whether felt viscerally or arrived at through reasoning — and priorities have genuinely reorganized around answering it. Risk: the \"selfless giver\" pattern the book describes — generosity without adequate self-protection, ending in exhaustion or resentment."
        },
        "low_high": {
          "name": "the closed loop",
          "text": "Others' suffering exerts little moral pull, and priorities run toward the self's own concerns. The most self-contained anchor on this pair — not necessarily hostile, simply organized around the self, with no countervailing force from either axis pulling attention elsewhere."
        },
        "low_low": {
          "name": "duty without the pull",
          "text": "Others receive priority even though their suffering exerts relatively little moral pull. The giving comes from role, obligation, or principle rather than from the suffering itself. Reasoning alone does not place someone here: a person who reasons their way to real moral concern belongs in Empathy + Altruism. Measure how much the suffering matters, not how the person got there."
        },
        "high_high": {
          "name": "moved but not moved to act",
          "text": "Others' suffering registers as a genuine moral pull, but when interests compete, priority tends to flow toward the self. Helping still happens; its cost and the context shape whether the pull wins. A harder anchor to spot than the others because the concern is authentic — the gap appears specifically where concern would need to become sacrifice. Reads to others as inconsistency (\"you seemed to care — why didn't you help?\") rather than as coldness."
        }
      }
    },
    "empathy|conscientiousness": {
      "axes": [
        "empathy",
        "conscientiousness"
      ],
      "anchors": {
        "high_high": {
          "name": "the sustained caregiver",
          "text": "Moral concern for others is channeled through structure rather than dissipating in the moment — commitments to help are followed through on schedule, over time, not just in the emotional peak when the need was first felt. This is the profile most likely to build durable caregiving systems (recurring donations, consistent presence, reliable follow-up) rather than one-off responses to acute appeals."
        },
        "low_low": {
          "name": "the uncommitted moment",
          "text": "Low moral pull and low structural follow-through combine to produce minimal, unpredictable engagement with others' needs — not from active refusal, but because neither the caring nor the discipline is present to generate or sustain a response. When help is given here, it tends to be spontaneous and situational rather than principled or planned."
        },
        "high_low": {
          "name": "the responsive but unreliable helper",
          "text": "The moral pull is real and can be intense in the moment — dropping everything for a friend's crisis — but lacks the structural follow-through to sustain it once the acute moment passes. This produces a specific relational friction: people the person has helped may feel the help was genuine but incomplete, because the plan for what comes next never solidified."
        },
        "low_high": {
          "name": "the reliable non-responder",
          "text": "Structure and follow-through are strong, but not organized around others' emotional needs — commitments are honored, systems maintained, but not because someone's suffering created a pull to act. This can look, from a distance, like dependable support; up close, the reliability is about the system, not about the person being helped."
        }
      }
    },
    "empathy|agency": {
      "axes": [
        "empathy",
        "agency"
      ],
      "anchors": {
        "high_high": {
          "name": "the advocate",
          "text": "Moral concern combines with a willingness to act on it directly and assertively — initiating on someone else's behalf rather than waiting to be asked, intervening in conflict, pushing for a resource or a change because someone's suffering demands it. This is close to the book's description of the hyper-attuned mediator's cousin: not detecting tension (that's Social Attunement) but acting decisively once genuine need is recognized."
        },
        "low_low": {
          "name": "the passive bystander",
          "text": "Neither the moral pull nor the assertive instinct is present. Not cruelty — closer to genuine non-involvement: a low likelihood of either noticing an obligation to act or pushing to act on it even if pointed out. The book's low-agency description (\"assertion feels dangerous\") compounds with detachment's lack of motivational charge to produce the least interventionist anchor on this pair."
        },
        "high_low": {
          "name": "the quiet carrier",
          "text": "Real, sometimes intense concern for others' suffering, but expressed through support and deference rather than direct intervention — absorbing others' distress, adjusting one's own plans, without asserting what the situation might actually require. Risk: the person can end up carrying significant emotional weight for others while having little influence over the conditions causing it, since assertion itself feels costly."
        },
        "low_high": {
          "name": "the unsentimental driver",
          "text": "Directive and confident, comfortable with power, and acting without being slowed by the emotional cost decisions impose on others. Most often this is decisive leadership that doesn't need emotional buy-in to function — the turnaround executive, the commander who makes the hard call. The book's \"predatory dynamics\" warning applies at the edge, where this combines with strong Self-Focus and other people become instruments rather than constraints. Without that third ingredient, these two scores describe a style, not a danger."
        }
      }
    },
    "empathy|reactivity": {
      "axes": [
        "empathy",
        "reactivity"
      ],
      "anchors": {
        "high_high": {
          "name": "the flooded responder",
          "text": "Moral concern for others' suffering combines with a nervous system that amplifies whatever it registers — the felt pull to help arrives not as a quiet obligation but as urgent, sometimes overwhelming pressure. The book's discussion of high-reactivity vulnerability (guilt trips landing because the guilt is genuinely, viscerally felt) applies with particular force here, since the empathic pull gives manipulators a specific lever to pull."
        },
        "low_low": {
          "name": "the even keel",
          "text": "Low moral pull and low amplitude: others' suffering exerts little pull, and what does register is felt without escalating. The anchor furthest from urgency on this pair. Calm under pressure comes naturally here — though calm is not the same as handling a crisis well — and warmth may be in short supply."
        },
        "high_low": {
          "name": "the steady advocate",
          "text": "Genuine moral concern paired with a nervous system that doesn't flood — the person who cares as much as the highly reactive empathizer but can sit with someone's pain, or act on a cause, without being overwhelmed by it. Lower burnout risk makes sustained caregiving or advocacy more sustainable, though whether it is effective depends on other axes."
        },
        "low_high": {
          "name": "intensity on its own terms",
          "text": "Amplitude is high, but it isn't being generated by others' suffering — the person can be volatile, passionate, easily activated, while that activation runs on its own internal logic rather than on empathic concern. From outside this can be mistaken for empathy (visible emotional intensity reads as caring), but the book's distinction holds: Reactivity describes amplitude, not what the amplitude is about."
        }
      }
    },
    "social_attunement|self_orientation": {
      "axes": [
        "social_attunement",
        "self_orientation"
      ],
      "anchors": {
        "high_low": {
          "name": "the attentive giver",
          "text": "Rich social perception feeds directly into where resources and priority flow — this person doesn't just want to help, they accurately perceive who needs it and how, because the antenna is picking up the signal that the motivation then acts on. The book's description of hyper-attuned mediators (understanding not just what people say but what they need) combines here with genuine other-directed priority."
        },
        "low_high": {
          "name": "unaware and unmoved",
          "text": "Neither perceiving others' circumstances in detail nor prioritizing them if perceived. This is a low-friction anchor in one specific sense — the person isn't withholding attention from others so much as simply not generating much of either the perceptual or motivational material that would direct it there."
        },
        "high_high": {
          "name": "the instrumentalized read",
          "text": "Fine-grained social perception in service of self-directed goals — reading a room accurately and using that read for personal advantage, status, or control, echoing the book's con-artist anchor but generalized beyond Empathy specifically. The perceptual gift is intact; what it's aimed at is the self's own position."
        },
        "low_low": {
          "name": "care without a map",
          "text": "Strong other-directed motivation without the fine-grained perception to reliably know how to apply it. The intent to help is genuine and can be structural or systematic (echoing the book's altruism-through-systems examples), but the person is more likely to miss the specific, situational cues that would tell them help is currently needed, or in what form."
        }
      }
    },
    "social_attunement|conscientiousness": {
      "axes": [
        "social_attunement",
        "conscientiousness"
      ],
      "anchors": {
        "high_high": {
          "name": "the calibrated planner",
          "text": "Rich social input feeds into disciplined, structured follow-through — plans and systems are built with accurate awareness of the social terrain they'll operate in, rather than in isolation from it. This is a strong anchor for effective mediation and negotiation infrastructure: the read informs the plan, and the plan is actually executed."
        },
        "low_low": {
          "name": "the double blind spot",
          "text": "Neither the social signal nor the structural follow-through is strong. Plans shift without much awareness of the social consequences of the shift — not from disregard, but because the information that would flag a problem (social) and the discipline that would correct for it (structural) are both thin. This is the anchor most prone to blindsiding others without any intent to do so."
        },
        "high_low": {
          "name": "reads the room, changes the plan anyway",
          "text": "Accurate, real-time social perception paired with low structural commitment — the person notices exactly what's shifting in a room or relationship and adapts fluidly, sometimes to the frustration of more conscientious collaborators who experience the resulting changes as unreliability rather than responsiveness. The book's \"adaptive attunement\" middle-ground language is relevant context here, though this anchor sits at the impulsive extreme rather than the balanced center."
        },
        "low_high": {
          "name": "the systems-first operator",
          "text": "Low social input, high structural discipline — plans and systems are built and executed reliably, but with less awareness of, or accommodation for, the social terrain they land in. The book's description of hypo-attunement finding \"greater cognitive resources available for systems, patterns, and details\" pairs naturally with conscientiousness here, often producing technically excellent execution that requires a more socially attuned partner or collaborator to land well with people."
        }
      }
    },
    "social_attunement|agency": {
      "axes": [
        "social_attunement",
        "agency"
      ],
      "anchors": {
        "high_high": {
          "name": "calibrated influence",
          "text": "Real-time social calibration combined with directive, confident assertion — reading which argument or appeal moves a given listener, and using it. Influence is precisely targeted; whether it serves the listener, the speaker, or a shared goal, and whether it stays honest, depends on other axes. Distinct from Empathy + Agentic (the advocate) because the driving force here is accurate perception in service of influence, not concern for the other person's wellbeing."
        },
        "low_low": {
          "name": "quiet and unaware",
          "text": "Low social perception and low assertive instinct combine into a profile that neither reads the room nor tries to steer it — comfortable receding, and largely unaware of what it might mean to lead even if the opportunity arose. Low-friction in group settings, but also the anchor least likely to notice when its own accommodation is being exploited."
        },
        "high_low": {
          "name": "the informed non-leader",
          "text": "Accurate, fine-grained social perception that does not translate into assertion — the person may see exactly what a group needs, who's uncomfortable, where the tension sits, but experiences directly acting on that information as costly or unnatural. Often ends up functioning as an informal advisor to whoever does lead, supplying the read without claiming the authority."
        },
        "low_high": {
          "name": "blunt initiative",
          "text": "The opposite pairing: low social read paired with comfortable, direct assertion — explicit logic and direct, transactional interaction rather than socially calibrated persuasion. Confidence and initiative are present, but not calibrated to social nuance; influence here comes from clarity and directness rather than precision-targeted reading of the listener."
        }
      }
    },
    "social_attunement|reactivity": {
      "axes": [
        "social_attunement",
        "reactivity"
      ],
      "anchors": {
        "high_high": {
          "name": "intensely engaged",
          "text": "The book names this combination directly: someone receiving an enormous amount of social information and responding to all of it at high amplitude — \"intensely engaged, emotionally expressive, perhaps charismatic, and sometimes exhausting,\" both to the person and to those around them."
        },
        "low_low": {
          "name": "the quiet operator",
          "text": "Low social input, low amplitude — the anchor least stirred by the social environment in either direction. This can read as profound calm or as disengagement depending on context; the book's framing suggests it's neither pretense nor deficiency, simply a nervous system receiving and amplifying comparatively little."
        },
        "high_low": {
          "name": "the steady reader",
          "text": "The book's own named anchor: a skilled therapist who perceives every nuance in a client's distress with extraordinary precision while remaining emotionally steady throughout. The antenna and the amplifier are explicitly decoupled here — full perceptual input, contained response — which the book treats as a distinct and valuable configuration rather than a lesser version of high reactivity."
        },
        "low_high": {
          "name": "internally driven intensity",
          "text": "The book's own named anchor: someone who receives relatively little of the social signal around them, but what does get through produces a strong response — emotional intensity driven more by internal state than by the social environment. Can look, from outside, similar to Hyper-Attuned + High-Reactive, but the trigger for the intensity is different: internally generated rather than socially read."
        }
      }
    },
    "self_orientation|conscientiousness": {
      "axes": [
        "self_orientation",
        "conscientiousness"
      ],
      "anchors": {
        "low_high": {
          "name": "the systematic giver",
          "text": "Other-directed motivation channeled through discipline and planning — structural, systematic giving (building durable institutions or processes) rather than personal, case-by-case giving. Generosity here is sustained and scalable precisely because it's organized rather than dependent on the emotional peak of any single moment."
        },
        "high_low": {
          "name": "chasing the next thing",
          "text": "Attention and resources center on the self, and follow-through on any given commitment (to self or others) is inconsistent — priorities shift with whatever the self wants right now rather than tracking toward a sustained personal or shared goal. Distinct from Self-Focus + Conscientious below in that even self-serving plans here are prone to abandonment."
        },
        "low_low": {
          "name": "generous in the moment",
          "text": "Other-directed motivation without the structural follow-through to sustain it — genuine, spontaneous generosity (dropping everything to help) without the systems that would make the help durable or repeatable. This is close to Empathy + Impulsive (the responsive but unreliable helper) but the driver is priority-of-resources rather than moral pull specifically."
        },
        "high_high": {
          "name": "the disciplined self-builder",
          "text": "Attention centers on the self, pursued with real structure and follow-through — ambition, personal achievement, and long-term self-interest executed systematically. The book is explicit that self-orientation is not itself pathological; paired with conscientiousness this is often simply effective, sustained personal achievement, with the same caveat as elsewhere that the edge case is when others' interests stop counting as a constraint at all."
        }
      }
    },
    "self_orientation|reactivity": {
      "axes": [
        "self_orientation",
        "reactivity"
      ],
      "anchors": {
        "low_high": {
          "name": "the urgent cause",
          "text": "Other-directed motivation combined with high emotional amplitude — a moral wrong doesn't just register as something to address eventually, it produces the kind of visceral disturbance the book describes as \"fuel for art, activism, or reform.\" Generosity here can arrive with real force and urgency, at some risk of the same burnout pattern the book flags for high reactivity generally."
        },
        "high_low": {
          "name": "unmoved and unmoving",
          "text": "Attention centers on the self, and little produces a strong internal response either way. A calm, low-urgency profile; others' needs, when they compete with one's own, rarely generate the pressure that would redirect priority."
        },
        "low_low": {
          "name": "principled and composed",
          "text": "Other-directed priority sustained without the intensity spikes that can burn out the high-reactive altruist. The pull to give may be strong; it simply doesn't arrive as alarm. Well suited to the sustained, undramatic service the book associates with structural rather than crisis-driven giving."
        },
        "high_high": {
          "name": "the volatile self",
          "text": "Attention centers on the self, and threats to the self's interests, image, or standing produce a strong internal response — often more than the event warrants. Typically this means being easily stung, quick to feel slighted, slow to settle. The book's vulnerable-narcissism fragility sits at the far edge, not the center."
        }
      }
    },
    "conscientiousness|agency": {
      "axes": [
        "conscientiousness",
        "agency"
      ],
      "anchors": {
        "high_high": {
          "name": "the executive",
          "text": "Discipline and structure combined with comfort initiating and directing — plans are made and then actively driven forward rather than passively hoped for. This is close to what most organizations picture as strong leadership: decisive, systematic, willing to own outcomes."
        },
        "low_low": {
          "name": "carried along",
          "text": "Low structural follow-through and low assertive instinct combine into a profile that tends to go where circumstances (or other people) lead, without either a personal plan or the initiative to counter one imposed from outside. Not passivity exactly — genuine present-moment engagement can be real here — but direction tends to come from elsewhere."
        },
        "high_low": {
          "name": "the reliable second",
          "text": "Strong discipline and follow-through in service of someone else's direction rather than one's own — the book's exemplary-follower pattern (Kelley's \"active and accommodating\" description) combined with real structural competence. This is often the person actually executing a plan that someone more agentic set, and doing so more reliably than the agentic partner could alone."
        },
        "low_high": {
          "name": "bold and unstructured",
          "text": "Comfort initiating and asserting, without the structural follow-through to sustain a given direction once momentum fades — decisive in the moment, prone to changing course as new impulses arrive. Can produce real creative or entrepreneurial leaps (comfort with risk, willingness to act on incomplete information) at the cost of consistent execution once the initial decisiveness has been spent."
        }
      }
    },
    "agency|reactivity": {
      "axes": [
        "agency",
        "reactivity"
      ],
      "anchors": {
        "high_high": {
          "name": "the passionate leader",
          "text": "Comfort with initiative and assertion combined with high emotional amplitude — leadership or advocacy pursued with visible intensity, capable of mobilizing others through the force of the reaction itself, not just the position taken. Risk: the same intensity that mobilizes can also escalate conflict faster than a lower-amplitude leader would, and success can compound overconfidence, per the book's account of the arrogance feedback loop."
        },
        "low_low": {
          "name": "the unshaken deferrer",
          "text": "Comfort receding paired with a nervous system that isn't easily activated — a profile that neither seeks the lead nor is destabilized by much of anything. Genuinely stabilizing in group settings (the book's finding that even one accommodating, low-drama member improves team cohesion), at the cost of rarely supplying the urgency that would push a group to act."
        },
        "high_low": {
          "name": "the calm commander",
          "text": "Directive and confident, without the amplitude that would make that direction volatile — the book's socialized-power pattern, calibrating assertiveness to context, steady under pressure, so decisions aren't distorted by alarm. Closest to what the book describes as \"flexible leadership\": authority exercised without the emotional cost of high reactivity layered on top."
        },
        "low_high": {
          "name": "the pressured deferrer",
          "text": "Discomfort with assertion combined with high emotional amplitude — the book's description of assertion itself feeling \"stressful\" for the accommodating end is intensified here: conflict or the prospect of it can produce real emotional flooding, even though the response to that flooding is typically further withdrawal rather than confrontation. This is the anchor most likely to absorb group tension internally at real personal cost, since the amplitude registers the strain even though the disposition doesn't act on it directly."
        }
      }
    }
  },
  "single": {
    "social_attunement": {
      "high": {
        "name": "the open antenna",
        "text": "Social information arrives constantly and largely automatically: the hesitation, the forced smile, who is avoiding whom. With the other axes balanced, the defining feature is how much is taken in, not what is done with it; the read informs rather than drives. Strength: social prediction and early detection of tension; people feel seen. Cost: the scan runs whether or not it's wanted, and the mind always reading the room has less bandwidth left for being in it."
      },
      "low": {
        "name": "the thin signal",
        "text": "Much of the social undercurrent simply doesn't arrive — the perfectly pleasant evening without realizing there were currents to miss. This is not indifference: when a need is stated plainly, the person's otherwise moderate concern engages normally. Strength: independent judgment, relative immunity to unspoken group pressure, deep focus, saying what they actually think. Cost: unintended offense that stays invisible unless explained, and missed signals that others misread as not caring."
      }
    },
    "empathy": {
      "high": {
        "name": "the weight of it",
        "text": "Others' suffering registers as something that matters and demands a response, whether felt viscerally or reached through reasoning. With the rest balanced, that concern is neither amplified into flooding nor automatically converted into sacrifice. Risk: concern that outruns what can be relieved; the task is making concern livable."
      },
      "low": {
        "name": "information, not weight",
        "text": "Others' suffering is registered but carries relatively little moral pull: appropriate sympathy, practical accommodation, then moving on. Neither callous nor dishonest. Strength: judgment not captured by the most emotionally compelling story — the judge, the journalist, the crisis responder. The book's warning about detachment hardening into habitual indifference sits at the far edge and cannot be read from this score alone."
      }
    },
    "self_orientation": {
      "low": {
        "name": "service as default",
        "text": "When interests compete, priority tends to flow toward others or toward a cause beyond the self — a settled direction rather than a feeling. Risk: the selfless giver, generosity without adequate self-protection ending in exhaustion or resentment; the healthy form is the \"otherish\" giver who balances concern for others with concern for themselves."
      },
      "high": {
        "name": "the self as anchor",
        "text": "When interests compete, priority tends to flow toward one's own needs, goals, and standing. In the book's terms this is healthy self-regard far more often than narcissism: ambition, independence, the willingness to protect one's own interests. The pathological edge — where other people's interests consistently cease to matter — cannot be read from this score."
      }
    },
    "conscientiousness": {
      "high": {
        "name": "the long view",
        "text": "Present action is shaped by future consequence: plans are made and kept, gratification is deferred, commitments are honored after motivation has faded. Strength: reliability that creates trust. Cost: structure hardening into perfectionism — the itinerary becoming an anchor rather than a compass, reaching the summit without noticing the view."
      },
      "low": {
        "name": "the present tense",
        "text": "Fully inhabited by the present; plans feel constraining and the future feels abstract. Strength: starting, experimenting, genuine presence, comfort with risk. Cost: many starts and fewer finishes, with consequences that arrive later. External structure often supplies what the disposition doesn't. What looks like impulsivity can also be an adaptation to an unpredictable environment rather than a flaw."
      }
    },
    "agency": {
      "high": {
        "name": "the one who moves first",
        "text": "Initiates rather than waits, decides with incomplete information, claims space without needing permission. With Empathy and Self-Orientation balanced, nothing here says whom the initiative serves. Strength: momentum and direction when a group stalls. Cost: others can feel directed rather than collaborated with; genuine listening is the growth edge."
      },
      "low": {
        "name": "the one who makes room",
        "text": "Supports, builds on others' ideas, finds common ground; assertion itself feels costly. Strength: defuses tension — the exemplary follower whose presence improves group cohesion. Cost: credit taken, needs suppressed, resentment accumulating quietly. Often partly learned in environments where assertion carries a real price, so the visible behavior is not necessarily the dispositional center."
      }
    },
    "reactivity": {
      "high": {
        "name": "full volume",
        "text": "Whatever arrives, the internal response is large, fast, and slow to settle — in both directions: grief more devastating, joy more transporting. Whether it shows depends on expression, which is shaped separately (Chapter 7). Strength: passionate engagement, and an urgency that won't let problems be quietly buried. Cost: minor stressors felt as emergencies, and an amplitude that manipulation can exploit."
      },
      "low": {
        "name": "quiet waters",
        "text": "Responses arrive smaller and settle faster: calm where others panic. Not suppression — the system genuinely generates less. Strength: composure under pressure. Cost: being read as cold, and the absence of alarm is not the absence of danger, so harmful situations may be tolerated too long. Note that someone who looks calm may be high-registration and low-expression; this score describes what is felt, not what shows."
      }
    }
  },
  "balanced": {
    "name": "the wide middle",
    "text": "No dimension pulls far from center: on every axis the dispositional center sits in the balanced middle. This is not an absence of personality but a configuration in which no single pull dominates — closer, on each axis, to the book's adaptive middle than to either end. The reading should describe the slight leans the scores do show without inflating them into traits. A balanced center says where someone tends to rest, not how far they can move: it does not by itself mean wide bandwidth or easy adaptability. Strength: no strong default works against the person in most situations, and they are often easy to work alongside. Cost: others may find them harder to read, and a group looking for a strong pull in some direction may not find it here. Middle scores can also come from answering inconsistently, so the reading should stay modest."
  },
  "modifierDefaults": {
    "social_attunement": {
      "summary": "shifts how much social information the primary interaction is acting on",
      "hypothesis": "Social Attunement doesn't change *what* the primary interaction is about — it changes how much social information is detected and considered as it runs. More input does not guarantee accurate interpretation. At the high end, whatever the primary dynamic is (an advocate's intervention, a directive-server's initiative, a quiet self-protector's going-along) operates with fine-grained, real-time awareness of the social terrain it's acting in. At the low end, the same primary dynamic operates on thinner social information — not absent, just less complete — making it more prone to misfiring or being misread by the people on the receiving end. Scales continuously with the person's actual Attunement score, in either direction from the primary pair's own center."
    },
    "empathy": {
      "summary": "shifts how much others' suffering matters within the primary dynamic",
      "hypothesis": "Empathy changes how strong the moral pull of others' suffering is inside whatever the primary mechanism is doing — whether that pull is felt viscerally or reached through reasoning — without changing the mechanism itself. High Empathy as a modifier means others' suffering weighs on the dynamic as something that demands a response; low Empathy (detachment) means the same mechanism runs with little of that pull. It does not by itself decide whose interests win (that is Self-Orientation) or whether action follows (that depends on Agency, Conscientiousness, and capacity). Low Empathy is not, on its own, instrumental or exploitative."
    },
    "self_orientation": {
      "summary": "shifts whose interest the primary interaction ultimately serves",
      "hypothesis": "Self-Orientation modifies *whose benefit* the primary dynamic is organized around, independent of the primary mechanism itself. High altruism as a modifier bends the primary interaction toward serving other people or a cause beyond the self; high self-focus bends the same mechanism toward personal advancement, status, or protection. Unlike Empathy (which is about how much others' suffering matters), this is about where resources and priority flow once something registers — the book's own distinction between the two axes (Chapter 4: \"does it matter to me that you are suffering\" vs. \"when I act, do I subordinate my interests to yours\")."
    },
    "conscientiousness": {
      "summary": "shifts whether the primary interaction is sustained over time or expressed only in the moment",
      "hypothesis": "Conscientiousness modifies the *durability* of the primary dynamic — whether it shows up as a one-time, high-intensity expression or as something planned, repeated, and reliably followed through on. High Conscientiousness as a modifier makes whatever the primary interaction is doing more likely to persist and compound over time (echoing the book's own \"sustained caregiver\" vs. \"responsive but unreliable helper\" distinction from Layer 2, generalized beyond the Empathy×Conscientiousness pair it was written for). Low Conscientiousness (impulsivity) makes the same primary dynamic more likely to appear vividly in a given moment and then not recur in the same form. Either way, it shapes planning and follow-through without determining the dynamic's moral purpose."
    },
    "agency": {
      "summary": "shifts whether the primary interaction is asserted/initiated or expressed through deference",
      "hypothesis": "Agency modifies the *stance* the primary dynamic is expressed from — actively initiated and directive at the high end, or expressed through support and accommodation of someone else's lead at the low end — without changing what the underlying dynamic is about, and without establishing leadership competence or ethical intent. This generalizes the shape already visible across several Layer 2 pairs (e.g., \"the directive server\" vs. \"service without a seat at the table\" both describe the same altruistic motivation expressed through opposite Agency stances)."
    },
    "reactivity": {
      "summary": "shifts the felt amplitude and duration of the primary interaction",
      "hypothesis": "Reactivity is the axis most likely to generalize cleanly as a modifier, because the book itself defines it as content-independent amplitude — \"it does not care what the input was... it simply describes the amplitude and duration of the nervous system's answer to whatever arrives.\" As a modifier, high Reactivity should make whatever the primary interaction is doing felt more intensely and for longer; low Reactivity should make the identical primary dynamic felt more calmly, without changing its underlying direction or content. Whether that intensity is visible is shaped separately by culture and learned behavior (Chapter 7), so urgency, visible expression, and volatility are possible outcomes, not guaranteed ones."
    }
  }
}
