// Runs the Layer 4 engine over the checked-in reference profiles and writes a
// distribution report: how often each primary rule fires, and what each
// profile's structured reading is. Evidence for #31, not validation.
//
//   npx tsx scripts/interpretation-report.ts

import { readFileSync, writeFileSync } from 'node:fs'
import { interpret, toEngineScores, PROTOCOL_VERSION } from '../src/lib/interpretation/compose'
import type { AxisKey } from '../src/lib/interpretation/types'

const SHORT: Record<AxisKey, string> = {
  social_attunement: 'SA', empathy: 'EM', self_orientation: 'SO', conscientiousness: 'CO', agency: 'AG', reactivity: 'RE',
}
const profiles = JSON.parse(readFileSync('data/famous-figures-profiles.json', 'utf8')) as
  { name: string; primary: string; scores: Record<AxisKey, number> }[]

const rows = profiles.map((p) => ({ p, r: interpret(toEngineScores(p.scores)) }))
const count = (f: (x: (typeof rows)[number]) => boolean) => rows.filter(f).length
const pct = (n: number) => `${n} (${Math.round((100 * n) / rows.length)}%)`

const rules = ['tied_top_pairs', 'tied_top_reduced', 'top_with_runner_up', 'single_axis'] as const
const ruleLabel: Record<(typeof rules)[number], string> = {
  tied_top_pairs: '2–3 axes tied for most extreme',
  tied_top_reduced: '4+ tied (axis-order fallback used)',
  top_with_runner_up: 'one top axis + runner-up(s)',
  single_axis: 'single-axis reading',
}

const lines: string[] = []
lines.push('# Interpretation engine: reference-profile run', '')
lines.push(`Protocol \`${PROTOCOL_VERSION}\`, reference \`${rows[0].r.referenceVersion.layer2}\` / \`${rows[0].r.referenceVersion.layer3}\`. Generated by \`npx tsx scripts/interpretation-report.ts\`.`, '')
lines.push(`Input: the ${rows.length} aggregate profiles in \`data/famous-figures-profiles.json\` (author-assigned 1–10 integer scores). This shows how the decided rules behave on real-shaped profiles. It is **not** validation (#31): that needs people with strong ground truth, and checks of the composed reading, not just which rule fired.`, '')
lines.push('## How often each rule fires', '', '| Rule | Profiles |', '| --- | --- |')
for (const rule of rules) lines.push(`| ${ruleLabel[rule]} | ${pct(count((x) => x.r.primary.rule === rule))} |`)
lines.push('', '| Primary type | Profiles |', '| --- | --- |')
for (const type of ['pair', 'co_primary_pairs', 'single_axis'] as const) lines.push(`| ${type} | ${pct(count((x) => x.r.primary.type === type))} |`)
lines.push('', `Profiles with 3 co-primary pairs: ${pct(count((x) => x.r.primary.pairs.length === 3))}. Fully balanced profiles: ${pct(count((x) => x.r.flags.includes('all_balanced')))}.`, '')

lines.push('## Every profile', '', '| Name | Scores (SA EM SO CO AG RE) | Rule | Primary reading | Top modifier |', '| --- | --- | --- | --- | --- |')
for (const { p, r } of rows) {
  const scores = r.positions.map((x) => x.score).join(' ')
  const reading = r.primary.single
    ? `${SHORT[r.primary.single.axis]} ${r.primary.single.pole}: "${r.primary.single.name}"`
    : r.primary.pairs.map((pr) => `${pr.axes.map((a) => SHORT[a]).join('×')}: "${pr.anchors[0].name}" ${Math.round(pr.anchors[0].weight * 100)}%`).join('; ')
  const m = r.modifiers[0]
  lines.push(`| ${p.name} | ${scores} | ${r.primary.rule} | ${reading} | ${m ? `${SHORT[m.axis]} ${m.signed > 0 ? '+' : ''}${m.signed.toFixed(2)}` : '—'} |`)
}
lines.push('')
writeFileSync('docs/interpretation-engine-report.md', lines.join('\n'))
console.log(lines.slice(0, 22).join('\n'))
